
 CREATE VIEW  [QUALIFIED TEACHERS IN POOREST DISTRICT] AS
 --WHERE 1 = POOREST DISTRICT AND 0 IS NOT
 
SELECT HTTYPSCH , HTPRDIST,PROVINCE, COUNT (HTLVLEDC) AS 'QUALIFIED'
FROM VIETNAM_WAVE_1_HEADTEACHER AS HT
JOIN VIETNAM_WAVE_1_FAMILY AS FA
ON HT.UNIQUEID=FA.UNIQUEID
GROUP BY HTTYPSCH, HTPRDIST
HAVING COUNT(HTLVLEDC) >=3

--QUESTION 1
--HOW MANY OF THE STUDENTS ARE IN THE 62 POOREST DISTRICTS?
CREATE PROCEDURE STUDENTS_WITH_QUALIFIED_TEACHERS
AS
BEGIN
SELECT HTTYPSCH = CASE WHEN HTTYPSCH = 1 THEN 'GOVERNMENT' WHEN HTTYPSCH = 2 THEN 'PRIVATE'  END, HTPRDIST = CASE WHEN HTPRDIST = 0 THEN 'NO' WHEN HTPRDIST = 1 THEN 'YES' WHEN HTPRDIST = 2 THEN 'DO NOT KNOW' END
, COUNT (HTLVLEDC) AS 'STUDENTS_WITH_QUALIFIED_TEACHERS'
FROM VIETNAM_WAVE_1_HEADTEACHER
WHERE HTPRDIST = 1
GROUP BY HTTYPSCH, HTPRDIST
HAVING COUNT(HTLVLEDC) >=3
END



CREATE VIEW  [QUALIFIED TEACHERS IN POOREST DISTRICT] AS
SELECT HTTYPSCH = CASE WHEN HTTYPSCH = 1 THEN 'GOVERNMENT' WHEN HTTYPSCH = 2 THEN 'PRIVATE'  END, HTPRDIST = CASE WHEN HTPRDIST = 0 THEN 'NO' WHEN HTPRDIST = 1 THEN 'YES' WHEN HTPRDIST = 2 THEN 'DO NOT KNOW' END
, COUNT (HTLVLEDC) AS 'QUALIFIED'
FROM VIETNAM_WAVE_1_HEADTEACHER 
GROUP BY HTTYPSCH, HTPRDIST
HAVING COUNT(HTLVLEDC) >=3













CREATE VIEW  [QUALITY OF SCHOOL] AS
SELECT HTTYPSCH = CASE WHEN HTTYPSCH  = 1 THEN 'GOVERNMENT' WHEN HTTYPSCH  = 2 THEN 'PRIVATE' when HTTYPSCH > = 3 then 'N/A' END , HTFLSINF = CASE when HTFLSINF = 1 THEN 'NEVER/RARELY' when HTFLSINF = 2 THEN 'OCASSIONALLY' when HTFLSINF = 3 THEN 'OFTEN' END
,COUNT (HTFLSINF) AS POOR_SCHOOL_STRUCTURE
FROM VIETNAM_WAVE_1_HEADTEACHER AS H1
JOIN VIETNAM_WAVE_2_HEADTEACHER2 AS H2
ON H1.UNIQUEID=H2.UNIQUEID
WHERE HTFLSINF  >= 1






CREATE VIEW  [CHILDLABOUR BY PROVINCE] AS
SELECT STUDENTID, HTCHDLBR = CASE WHEN HTCHDLBR = 1 THEN 'Never/Rarely' WHEN HTCHDLBR = 2 THEN 'Occasionally' WHEN HTCHDLBR = 3 THEN 'Often' when HTCHDLBR > = 3 then 'N/A' END , PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END
FROM VIETNAM_WAVE_1_FAMILY AS F1
JOIN VIETNAM_WAVE_2_headteacher2 AS H2
ON F1.UNIQUEID=H2.UNIQUEID
WHERE HTCHDLBR IN (1,2,3)
ORDER BY HTCHDLBR














--QUESTION 2 HOW MANY CHILDREN'S SCHOOLING ARE AFFECTED BY CHILD LABOUR?
CREATE PROCEDURE CHILDLABOUR
AS
BEGIN
SELECT STUDENTID, HTCHDLBR = CASE WHEN HTCHDLBR = 1 THEN 'Never/Rarely' WHEN HTCHDLBR = 2 THEN 'Occasionally' WHEN HTCHDLBR = 3 THEN 'Often' when HTCHDLBR > = 3 then 'N/A' END , PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END
FROM VIETNAM_WAVE_1_FAMILY AS F1
JOIN VIETNAM_WAVE_2_headteacher2 AS H2
ON F1.UNIQUEID=H2.UNIQUEID
WHERE HTCHDLBR >= 2
END







CREATE VIEW  [hIGH ABILITY ] AS
SELECT  CLASSID, GENDER = CASE WHEN GENDER = 1 THEN 'MALE' WHEN GENDER = 2 THEN 'FEMALE' END , B2ACABMT, B3ACABEN , PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END
FROM VIETNAM_WAVE_1_IDENTITY AS ID1
JOIN VIETNAM_WAVE_2_CLASS2 AS C2
ON ID1.UNIQUEID=C2.UNIQUEID
JOIN VIETNAM_WAVE_1_FAMILY AS F1
ON F1.UNIQUEID=ID1.UNIQUEID
WHERE B2ACABMT > = 5 AND B3ACABEN > = 5
ORDER BY CLASSID





CREATE VIEW  [LOW ABILITY ] AS
SELECT  CLASSID, GENDER = CASE WHEN GENDER = 1 THEN 'MALE' WHEN GENDER = 2 THEN 'FEMALE' END , B2ACABMT, B3ACABEN , PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END
FROM VIETNAM_WAVE_1_IDENTITY AS ID1
JOIN VIETNAM_WAVE_2_CLASS2 AS C2
ON ID1.UNIQUEID=C2.UNIQUEID
JOIN VIETNAM_WAVE_1_FAMILY AS F1
ON F1.UNIQUEID=ID1.UNIQUEID
WHERE B2ACABMT > = 5 AND B3ACABEN > = 5
ORDER BY CLASSID





--QUESTION 3
--HOW MANY GIRLS OR BOYS HAVE AN ABILITY OF ABOVE  5?
CREATE PROCEDURE ABILITY_BY_GENDER
AS
BEGIN
SELECT COUNT (B2ACABMT)AS 'MATHS ABILITY', COUNT (B3ACABEN) AS 'ENGLISH ABILITY', GENDER = CASE WHEN GENDER = 1 THEN 'MALE' WHEN GENDER = 2 THEN 'FEMALE' END
FROM VIETNAM_WAVE_2_CLASS2 AS C3
JOIN VIETNAM_WAVE_1_IDENTITY AS ID3
ON C3.UNIQUEID=ID3.UNIQUEID
WHERE B2ACABMT >=5
GROUP BY GENDER
END





CREATE VIEW  [POOREST DISTRICT] AS
-- WHAT IS THE QUALITY OF TEACHERS IN DIFFERENT SCHOOLS ESSPECIALLY WHERE CHILD LABOUR  IS NOTICEABLE?
SELECT HTCHDLBR = CASE WHEN HTCHDLBR = 1 THEN 'Never/Rarely' WHEN HTCHDLBR = 2 THEN 'Occasionally' WHEN HTCHDLBR = 3 THEN 'Often' when HTCHDLBR > = 3 then 'N/A' END , HTLVLEDC = CASE WHEN HTLVLEDC = 1 THEN 'Upper secondary or equivalent' WHEN HTLVLEDC = 2 THEN 'Vocational training school' WHEN HTLVLEDC = 3 THEN 'College education' WHEN HTLVLEDC = 4 THEN 'University education (undergraduate)' WHEN HTLVLEDC = 5 THEN 'University education (postgraduate)' when HTLVLEDC = 99 then 'missing' END, PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END, LOCALITY = CASE WHEN LOCALITY = 1 THEN 'RURAL' WHEN LOCALITY = 2 THEN 'URBAN' END, HTTYPSCH = CASE WHEN HTTYPSCH = 1 THEN 'GOVERNMENT' WHEN HTTYPSCH = 2 THEN 'PRIVATE' WHEN HTTYPSCH = 3 THEN 'OTHER' END, HTPRDIST = CASE WHEN HTPRDIST = 0 THEN 'NO' WHEN HTPRDIST = 1 THEN 'YES' WHEN HTPRDIST = 2 THEN 'DO NOT KNOW' END
, HTEXCTCH = CASE WHEN HTEXCTCH = 0 THEN 'Never been an excellent teacher' WHEN HTEXCTCH = 1 THEN 'Yes, school level' WHEN HTEXCTCH = 2 THEN ' Yes, province level or higher' WHEN HTEXCTCH = 3 THEN 'Yes, district level' WHEN HTEXCTCH = NULL THEN ' N/A'END , HTFLSINF = CASE when HTFLSINF = 1 THEN 'NEVER/RARELY' when HTFLSINF = 2 THEN 'OCASSIONALLY' when HTFLSINF = 3 THEN 'OFTEN' END
FROM VIETNAM_WAVE_1_IDENTITY AS ID4
JOIN VIETNAM_WAVE_1_HEADTEACHER AS H5
ON ID4.UNIQUEID=H5.UNIQUEID
JOIN VIETNAM_WAVE_1_FAMILY AS FA3
ON ID4.UNIQUEID=FA3.UNIQUEID
JOIN VIETNAM_WAVE_2_HEADTEACHER2 AS HT2
ON ID4.UNIQUEID=HT2.UNIQUEID
WHERE HTPRDIST = 1

CREATE PROCEDURE SUMMARYOFINEQUALITY
AS
BEGIN
-- WHAT IS THE QUALITY OF TEACHERS IN DIFFERENT SCHOOLS ESSPECIALLY WHERE CHILD LABOUR  IS NOTICEABLE?
SELECT HTCHDLBR = CASE WHEN HTCHDLBR = 1 THEN 'Never/Rarely' WHEN HTCHDLBR = 2 THEN 'Occasionally' WHEN HTCHDLBR = 3 THEN 'Often' when HTCHDLBR > = 3 then 'N/A' END , HTLVLEDC = CASE WHEN HTLVLEDC = 1 THEN 'Upper secondary or equivalent' WHEN HTLVLEDC = 2 THEN 'Vocational training school' WHEN HTLVLEDC = 3 THEN 'College education' WHEN HTLVLEDC = 4 THEN 'University education (undergraduate)' WHEN HTLVLEDC = 5 THEN 'University education (postgraduate)' when HTLVLEDC = 99 then 'missing' END, PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END, LOCALITY = CASE WHEN LOCALITY = 1 THEN 'RURAL' WHEN LOCALITY = 2 THEN 'URBAN' END, HTTYPSCH = CASE WHEN HTTYPSCH = 1 THEN 'GOVERNMENT' WHEN HTTYPSCH = 2 THEN 'PRIVATE' WHEN HTTYPSCH = 3 THEN 'OTHER' END, HTPRDIST = CASE WHEN HTPRDIST = 0 THEN 'NO' WHEN HTPRDIST = 1 THEN 'YES' WHEN HTPRDIST = 2 THEN 'DO NOT KNOW' END
, HTEXCTCH = CASE WHEN HTEXCTCH = 0 THEN 'Never been an excellent teacher' WHEN HTEXCTCH = 1 THEN 'Yes, school level' WHEN HTEXCTCH = 2 THEN ' Yes, province level or higher' WHEN HTEXCTCH = 3 THEN 'Yes, district level' WHEN HTEXCTCH = NULL THEN ' N/A'END , HTFLSINF = CASE when HTFLSINF = 1 THEN 'NEVER/RARELY' when HTFLSINF = 2 THEN 'OCASSIONALLY' when HTFLSINF = 3 THEN 'OFTEN' END
FROM VIETNAM_WAVE_1_IDENTITY AS ID4
JOIN VIETNAM_WAVE_1_HEADTEACHER AS H5
ON ID4.UNIQUEID=H5.UNIQUEID
JOIN VIETNAM_WAVE_1_FAMILY AS FA3
ON ID4.UNIQUEID=FA3.UNIQUEID
JOIN VIETNAM_WAVE_2_HEADTEACHER2 AS HT2
ON ID4.UNIQUEID=HT2.UNIQUEID
END


--QUESTION4
--HOW MANY SCHOOLS ARE THERE IN THE POOREST DISTRICT
CREATE VIEW [TYPE OF SCHOOL IN POOREST DISTRICT ] AS
SELECT COUNT (HTTYPSCH) AS 'SCHOOL TYPE', HTPRDIST= CASE WHEN HTPRDIST = 1 THEN 'POOREST DISTRICT' WHEN HTPRDIST = 0 THEN 'NOT IN POOR DISTRICT' END
FROM VIETNAM_WAVE_1_HEADTEACHER AS H6
JOIN VIETNAM_WAVE_1_IDENTITY AS ID7
ON ID7.UNIQUEID=H6.UNIQUEID
WHERE LOCALITY IS NOT NULL AND LOCALITY = 1
GROUP BY HTPRDIST 
UNION
SELECT COUNT (HTTYPSCH) AS 'SCHOOL TYPE', HTPRDIST= CASE WHEN HTPRDIST = 1 THEN 'POOREST DISTRICT' WHEN HTPRDIST = 0 THEN 'NOT IN POOR DISTRICT' END
FROM VIETNAM_WAVE_1_HEADTEACHER AS H6
JOIN VIETNAM_WAVE_1_IDENTITY AS ID7
ON ID7.UNIQUEID=H6.UNIQUEID
WHERE LOCALITY IS NOT NULL AND LOCALITY = 2
GROUP BY HTPRDIST
END


--HOW MANY SCHOOLS ARE THERE IN THE POOREST DISTRICT
CREATE PROCEDURE ABILITY_BY_GENDER
AS
BEGIN
SELECT COUNT (HTTYPSCH) AS 'TOTAL SCHOOL', HTPRDIST= CASE WHEN HTPRDIST = 1 THEN 'POOREST DISTRICT' WHEN HTPRDIST = 0 THEN 'NOT IN POOR DISTRICT' END
FROM VIETNAM_WAVE_1_HEADTEACHER AS H6
JOIN VIETNAM_WAVE_1_IDENTITY AS ID7
ON ID7.UNIQUEID=H6.UNIQUEID
WHERE LOCALITY IS NOT NULL AND LOCALITY = 1
GROUP BY HTPRDIST 
UNION
SELECT COUNT (HTTYPSCH) AS 'TOTAL SCHOOL', HTPRDIST= CASE WHEN HTPRDIST = 1 THEN 'POOREST DISTRICT' WHEN HTPRDIST = 0 THEN 'NOT IN POOR DISTRICT' END
FROM VIETNAM_WAVE_1_HEADTEACHER AS H6
JOIN VIETNAM_WAVE_1_IDENTITY AS ID7
ON ID7.UNIQUEID=H6.UNIQUEID
WHERE LOCALITY IS NOT NULL AND LOCALITY = 2
GROUP BY HTPRDIST
END


CREATE PROCEDURE  [HIGH ABILITY ] AS
BEGIN
SELECT  CLASSID, GENDER = CASE WHEN GENDER = 1 THEN 'MALE' WHEN GENDER = 2 THEN 'FEMALE' END , B2ACABMT, B3ACABEN , PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END
FROM VIETNAM_WAVE_1_IDENTITY AS ID1
JOIN VIETNAM_WAVE_2_CLASS2 AS C2
ON ID1.UNIQUEID=C2.UNIQUEID
JOIN VIETNAM_WAVE_1_FAMILY AS F1
ON F1.UNIQUEID=ID1.UNIQUEID
WHERE B2ACABMT > = 5 AND B3ACABEN > = 5
END
ORDER BY CLASSID
END

CREATE PROCEDURE  [LOW ABILITY ] AS
BEGIN
SELECT  CLASSID, GENDER = CASE WHEN GENDER = 1 THEN 'MALE' WHEN GENDER = 2 THEN 'FEMALE' END , B2ACABMT, B3ACABEN , PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END
FROM VIETNAM_WAVE_1_IDENTITY AS ID1
JOIN VIETNAM_WAVE_2_CLASS2 AS C2
ON ID1.UNIQUEID=C2.UNIQUEID
JOIN VIETNAM_WAVE_1_FAMILY AS F1
ON F1.UNIQUEID=ID1.UNIQUEID
WHERE B2ACABMT > = 5 AND B3ACABEN > = 5
END
ORDER BY CLASSID
END






CREATE VIEW CHILDREN_EDUCATED_BACKGROUND AS
SELECT studentid, DAD_EDUC = CASE WHEN DAD_EDUC  = 0 THEN 'Never been to school'  when DAD_EDUC= 1 then 'Primary school (Greades 1-5)' when DAD_EDUC= 2 then 'Lowver secondary school (Grades 6-9)' when DAD_EDUC= 3 then 'Intermediate vocational training' WHEN DAD_EDUC= 4 THEN 'Upper secondary school (Grades 10-12)' when DAD_EDUC= 5 then 'Higher education (e.g. university/college or higher' when DAD_EDUC = 6 then 'Donot know' WHEN DAD_EDUC  = '99' THEN 'missing' WHEN DAD_EDUC  = '88' THEN 'N/A' end ,  MOM_EDUC = CASE WHEN MOM_EDUC = 0 THEN 'Never been to school'  when MOM_EDUC= 1 then 'Primary school (Greades 1-5)' when MOM_EDUC= 2 then 'Lowver secondary school (Grades 6-9)' when MOM_EDUC= 3 then 'Intermediate vocational training' WHEN MOM_EDUC = 4 THEN 'Upper secondary school (Grades 10-12)' when MOM_EDUC= 5 then 'Higher education (e.g. university/college or higher' when mom_educ = 6 then 'Dont know'  WHEN  MOM_EDUC  = 99 THEN 'missing' WHEN MOM_EDUC  = 88 THEN 'N/A' end  , PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END
FROM VIETNAM_WAVE_1_FAMILY
WHERE MOM_EDUC IN (2,3,4,5) AND DAD_EDUC IN (2,3,4,5)
ORDER BY PROVINCE













CREATE PROCEDURE  [CHILDREN_EDUCATED_PARENTS] AS
BEGIN
SELECT HTCHDLBR,studentid, DAD_EDUC = CASE WHEN DAD_EDUC  = 0 THEN 'Never been to school'  when DAD_EDUC= 1 then 'Primary school (Greades 1-5)' when DAD_EDUC= 2 then 'Lowver secondary school (Grades 6-9)' when DAD_EDUC= 3 then 'Intermediate vocational training' WHEN DAD_EDUC= 4 THEN 'Upper secondary school (Grades 10-12)' when DAD_EDUC= 5 then 'Higher education (e.g. university/college or higher' when DAD_EDUC = 6 then 'Donot know' WHEN DAD_EDUC  = '99' THEN 'missing' WHEN DAD_EDUC  = '88' THEN 'N/A' end ,  MOM_EDUC = CASE WHEN MOM_EDUC = 0 THEN 'Never been to school'  when MOM_EDUC= 1 then 'Primary school (Greades 1-5)' when MOM_EDUC= 2 then 'Lowver secondary school (Grades 6-9)' when MOM_EDUC= 3 then 'Intermediate vocational training' WHEN MOM_EDUC = 4 THEN 'Upper secondary school (Grades 10-12)' when MOM_EDUC= 5 then 'Higher education (e.g. university/college or higher' when mom_educ = 6 then 'Dont know'  WHEN  MOM_EDUC  = 99 THEN 'missing' WHEN MOM_EDUC  = 88 THEN 'N/A' end  , PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END
FROM VIETNAM_WAVE_1_FAMILY AS FY
JOIN VIETNAM_WAVE_2_HEADTEACHER2 AS HTC2
ON FY.UNIQUEID=HTC2.UNIQUEID
WHERE MOM_EDUC IN (2,3,4,5) AND DAD_EDUC IN (2,3,4,5) AND HTCHDLBR IN (2,3,4)
ORDER BY PROVINCE
END
	

CREATE PROCEDURE  [STUDENTS_PARENTS] AS
BEGIN
SELECT HTCHDLBR,studentid, DAD_EDUC = CASE WHEN DAD_EDUC  = 0 THEN 'Never been to school'  when DAD_EDUC= 1 then 'Primary school (Greades 1-5)' when DAD_EDUC= 2 then 'Lowver secondary school (Grades 6-9)' when DAD_EDUC= 3 then 'Intermediate vocational training' WHEN DAD_EDUC= 4 THEN 'Upper secondary school (Grades 10-12)' when DAD_EDUC= 5 then 'Higher education (e.g. university/college or higher' when DAD_EDUC = 6 then 'Donot know' WHEN DAD_EDUC  = '99' THEN 'missing' WHEN DAD_EDUC  = '88' THEN 'N/A' end ,  MOM_EDUC = CASE WHEN MOM_EDUC = 0 THEN 'Never been to school'  when MOM_EDUC= 1 then 'Primary school (Greades 1-5)' when MOM_EDUC= 2 then 'Lowver secondary school (Grades 6-9)' when MOM_EDUC= 3 then 'Intermediate vocational training' WHEN MOM_EDUC = 4 THEN 'Upper secondary school (Grades 10-12)' when MOM_EDUC= 5 then 'Higher education (e.g. university/college or higher' when mom_educ = 6 then 'Dont know'  WHEN  MOM_EDUC  = 99 THEN 'missing' WHEN MOM_EDUC  = 88 THEN 'N/A' end  , PROVINCE = CASE when PROVINCE = 1 THEN 'Ben Tre' when PROVINCE = 2 THEN 'Da Nang'  WHEN PROVINCE = 3  THEN 'Hung Yen' WHEN PROVINCE = 4 THEN 'Lao Cai' when PROVINCE = 5 THEN 'Phu Yen' END
FROM VIETNAM_WAVE_1_FAMILY AS FY
JOIN VIETNAM_WAVE_2_HEADTEACHER2 AS HTC2
ON FY.UNIQUEID=HTC2.UNIQUEID
ORDER BY PROVINCE
END


















